dist: trusty
sudo: false
language: r
cache: packages

env:
  global:
    - _R_CHECK_TESTS_NLINES_=999

before_script:
  - R --no-save <<< 'library("devtools"); document()'

r:
  - 3.2
  - 3.3
  - 3.4
  - devel
